CREATE TABLE IF NOT EXISTS retention_policies (
    id SERIAL PRIMARY KEY,
    repository VARCHAR(255) UNIQUE NOT NULL,
    keep_n INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
