
services:

  postgres:
    image: postgres:16
    container_name: registry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: registry
      POSTGRES_PASSWORD: registry123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - registry_net

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./backend/certs:/auth
      - registry_data:/var/lib/registry
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:6500/api/auth
      REGISTRY_AUTH_TOKEN_SERVICE: registry
      REGISTRY_AUTH_TOKEN_ISSUER: my-auth-server
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /auth/auth.cert
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: |
        - name: backend-webhook
          disabled: false
          url: http://localhost:6500/api/registry/webhook
          headers:
             Authorization: [Bearer webhook_internal]
          timeout: 500ms
          threshold: 5
          backoff: 1s
    restart: unless-stopped
    networks:
      - registry_net

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy_server
    command: server --listen 0.0.0.0:4954 --timeout 30m --db-repository ghcr.io/aquasecurity/trivy-db:2,mirror.gcr.io/aquasec/trivy-db:2
    ports:
      - "4954:4954"
    volumes:
      - trivy_cache:/root/.cache/trivy
    restart: unless-stopped
    networks:
      - registry_net

  backend:
    build: ./backend
    container_name: registry_backend
    ports:
      - "6500:6500"
    environment:
      PORT: 6500
      HOST: "0.0.0.0"
      REGISTRY_PUBLIC_URL: http://registry:5000
      REGISTRY_CONTAINER_NAME: registry
      # REGISTRY_HOST: ip:5000 mandetory field
      TRIVY_SERVER: http://trivy:4954
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: registry
      DB_PASS: registry123
      DB_NAME: registry
      
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123

    depends_on:
      - postgres
      - registry
    restart: unless-stopped
    networks:
      - registry_net

  frontend:
    build: ./frontend
    container_name: registry_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:6500
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - registry_net

networks:
  registry_net:
    driver: bridge

volumes:
  postgres_data:
  registry_data:
  trivy_cache: