
services:

  postgres:
    image: postgres:16
    container_name: registry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - registry_net

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./backend/certs:/auth
      - registry_data:/var/lib/registry
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: ${REGISTRY_AUTH_REALM}
      REGISTRY_AUTH_TOKEN_SERVICE: ${REGISTRY_AUTH_SERVICE}
      REGISTRY_AUTH_TOKEN_ISSUER: ${REGISTRY_AUTH_ISSUER}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: ${REGISTRY_AUTH_ROOTCERTBUNDLE}
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: |
        - name: backend-webhook
          disabled: false
          url: ${REGISTRY_WEBHOOK_URL}
          headers:
             Authorization: [Bearer webhook_internal]
          timeout: 500ms
          threshold: 5
          backoff: 1s
    restart: unless-stopped
    networks:
      - registry_net

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy_server
    command: server --listen 0.0.0.0:4954 --timeout 30m --db-repository ghcr.io/aquasecurity/trivy-db:2,mirror.gcr.io/aquasec/trivy-db:2
    ports:
      - "4954:4954"
    volumes:
      - trivy_cache:/root/.cache/trivy
    restart: unless-stopped
    networks:
      - registry_net

  backend:
    build: ./backend
    container_name: registry_backend
    ports:
      - "6500:6500"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
      REGISTRY_PUBLIC_URL: ${REGISTRY_PUBLIC_URL}
      REGISTRY_CONTAINER_NAME: ${REGISTRY_CONTAINER_NAME}
      REGISTRY_HOST: ${REGISTRY_HOST}
      TRIVY_SERVER: ${TRIVY_SERVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    depends_on:
      - postgres
      - registry
    restart: unless-stopped
    networks:
      - registry_net

  frontend:
    build: ./frontend
    container_name: registry_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - registry_net

networks:
  registry_net:
    driver: bridge

volumes:
  postgres_data:
  registry_data:
  trivy_cache:
